#!/usr/bin/env sh
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
source_dir="$root/plugins/pinentry"
build_dir="$source_dir/build"

cmake -S "$source_dir" -B "$build_dir" -G Ninja
cmake --build "$build_dir"
