#!/usr/bin/env sh
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
install_prefix=${PINENTRY_INSTALL_PREFIX:-"$HOME/.local"}

"$root/scripts/build-pinentry-plugin"
cmake --install "$root/plugins/pinentry/build" --prefix "$install_prefix"
