Include = /etc/paru.conf

[options]
Mode = arp
SudoLoop
BatchInstall
# Disabled: paru 2.1.0 mishandles CleanAfter for local PKGBUILD repositories.
# CleanAfter

[local-pkgbuilds]
Path = /home/luke/Projects/pkgbuilds
Depth = 2
GenerateSrcinfo
