# --- Streaming ---
# Set the preferred resolution for streaming video.
ytdl-format=bestvideo[height<=?1080]+bestaudio/best

# --- Performance ---
# Enable hardware decoding for video. 'auto-safe' avoids problematic codecs.
hwdec=auto-safe

# --- Usability ---
# Save the playback position on quit, to resume later.
save-position-on-quit
# Add files in directory to playlist and auto-play next file
load-unsafe-playlists=yes
# Better OSD messages
osd-playing-msg="${playlist-pos-1}/${playlist-count}: ${filename}"
# Smooth video timing
video-sync=display-resample
# Scale subtitles nicely
sub-font-size=42
sub-font='Inter'

#force mpv to use yt-dlp first
ytdl=yes
script-opts=ytdl_hook-try_ytdl_first=yes
