wallpaper {
    monitor = DP-2
    path = ~/storage/Pictures/mazda-rx7-modified-4k-kx-2560x1440.jpg
}
wallpaper {
    monitor = DP-1
    path = ~/storage/Pictures/mazda-rx7-modified-4k-kx-2560x1440.jpg
}

splash = false
