# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/

# Rendered text in all widgets supports pango markup (e.g. <b> or <i> tags).
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks

# Shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace.

# You can get started by copying this config to ~/.config/hypr/hyprlock.conf.

$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    # path = screenshot # Takes a screenshot of your current workspace
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 1.0)
    outer_color = rgba(33ccffff) rgba(00ff99ff) 45deg
    check_color = rgba(00ff99ff) rgba(ff6633ff) 120deg
    fail_color = rgba(ff6633ff) rgba(ff0066ff) 40deg
    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15
    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL # Displays the PAM error message on failed attempts
    dots_spacing = 0.3
    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # Displays the current time
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}

# USERNAME
label {
    monitor =
    text = Hi there, $USER # Displays a welcome message with your username
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = Noto Sans
    position = 0, 120
    halign = center
    valign = center
}
